**Indexing**

In [ ]:
import numpy as np

In [ ]:
var = np.array([1,2,3,4])

print(var[2])
print(var[-3])

3
2


In [ ]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])
print(var1[1,1])

[[9 8 7]
 [4 5 6]]
2

7
5


In [ ]:
var2 = np.array([[[1,2],[5,7]]])
print(var2)
print(var2.ndim)
print()

print(var2[0,1,1])
print(var2[0,0,1])

[[[1 2]
  [5 7]]]
3

7
2


**Slicing**

In [ ]:
var = np.array([1,2,4,5,6,7,9,8])
#               0,1,2,3,4,5,6,7

print(var)
print()

print(var[::2])
print(var[0:5:2])

[1 2 4 5 6 7 9 8]

[1 4 6 9]
[1 4 6]


In [ ]:
var1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(var1)
print(var1.ndim)
print()

print("7 to 9 :",var1[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2

7 to 9 : [7 8 9]


**Iteration**

In [ ]:
var = np.array([4,5,6,7,8,9,10])
print(var)
print()

for i in var:
  print(i)

[ 4  5  6  7  8  9 10]

4
5
6
7
8
9
10


In [ ]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()

for i in var1:
  print(i)
print()

for k in var1:
  for l in k:
    print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
  for j in i:
    for k in j:
      print(k)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
  print(i)

print()

for i in np.nditer(var3,flags = ["buffered"], op_dtypes = ["S"]):
  print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4

b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


**Copy vs View**

In [ ]:
var = np.array([1,2,3,4])

co = var.copy()

var[1] = 40

print("var :",var)
print("copy :",co)


var : [ 1 40  3  4]
copy : [1 2 3 4]


In [ ]:
var1 = np.array([1,2,3,4])

vi = var1.view()

var1[1] = 40

print("var1 :",var1)
print("view :",vi)

var1 : [ 1 40  3  4]
view : [ 1 40  3  4]


**Join Array**

In [ ]:
var = np.array([1,2,3,4])
var1 = np.array([4,5,6,7])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 4 5 6 7]


In [ ]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[4,5],[6,7]])

ar_new = np.concatenate((vr,vr1),axis=1)
ar_new1 = np.concatenate((vr,vr1),axis=0)

print(vr)
print()
print(vr1)
print()
print(ar_new)
print()
print(ar_new1)

[[1 2]
 [3 4]]

[[4 5]
 [6 7]]

[[1 2 4 5]
 [3 4 6 7]]

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([4,5,6,7])

a_new = np.stack((var_1,var_2))
a_new1 = np.hstack((var_1,var_2))  #row
a_new2 = np.vstack((var_1,var_2))  #columns
a_new3 = np.dstack((var_1,var_2))  #height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 2 3 4]
 [4 5 6 7]]

[1 2 3 4 4 5 6 7]

[[1 2 3 4]
 [4 5 6 7]]

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]


**Split array**

In [ ]:
var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print()
print(ar)
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]
[3 4]
[5 6]


In [ ]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print(type(ar1))
print(ar1[0])
print(ar1[1])
print(ar1[2])
print()
print(ar2)
print()
print(ar2[0])
print(ar2[1])
print(ar2[2])

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]]
[[3 4]]
[[5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]

[[1]
 [3]
 [5]]
[[2]
 [4]
 [6]]
[]


**Search**

In [ ]:
var = np.array([1,2,3,4,2,6,2,7,8,9])
#index          0,1,2,3,4,5,6,7,8,9

x = np.where(var == 2)
x1 = np.where((var/2) == 0)
x2 = np.where((var%2) == 0)

print(x)
print()
print(x1)
print()
print(x2)

(array([1, 4, 6]),)

(array([], dtype=int64),)

(array([1, 3, 4, 5, 6, 8]),)


In [ ]:
var1 = np.array([1,2,4,6,7,8,9,10])
#index           0,1,2,3,4,5,6

x1 = np.searchsorted(var1,6)
x2 = np.searchsorted(var1,3,side="right")
x3 = np.searchsorted(var1,[4,5,6],side="right")

print(x2)
print(x1)
print(x3)

2
3
[3 3 4]


**Sort**

In [ ]:
var_1 = np.array([5,9,3,1,4,12,56,44,32,11])

print(np.sort(var_1))

[ 1  3  4  5  9 11 12 32 44 56]


In [ ]:
var_2 = np.array(["d","a","c","f"])

print(np.sort(var_2))

['a' 'c' 'd' 'f']


In [ ]:
var_3 = np.array([[5,9,3],[1,4,12],[56,44,32]])

print(np.sort(var_3))

[[ 3  5  9]
 [ 1  4 12]
 [32 44 56]]


**Filter Array**

In [ ]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]

print(new_a)

['a' 'f']


**shuffle**

In [ ]:
var = np.array([1,2,3,4,5,6])

np.random.shuffle(var)

print(var)

[4 2 1 6 3 5]


**Unique**

In [ ]:
var = np.array([1,2,3,5,4,5,3,6,7,6,8,9])

x = np.unique(var,return_index=True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  4,  3,  7,  8, 10, 11]), array([1, 1, 2, 1, 2, 2, 1, 1, 1]))


**Resize**

In [ ]:
var2 = np.array([1,2,3,5,4,5,3,6,7,6,8,9])

x = np.resize(var2,(3,4))
print(x)
print()



[[1 2 3 5]
 [4 5 3 6]
 [7 6 8 9]]



In [ ]:
var3 = np.array([1,2,3,4,5])

v = np.insert(var3 , 2 , 40)
v1 = np.insert(var3 , (2,4) , 40)

print(var3)
print()
print(v)
print()
print(v1)

[1 2 3 4 5]

[ 1  2 40  3  4  5]

[ 1  2 40  3  4 40  5]


In [ ]:
var1 = np.array([[1,2,3],[4,5,6]])

v2 = np.insert(var1 , 2, 6, axis=1)
v3 = np.insert(var1 , 2, 6, axis=0)
v4 = np.insert(var1 , 1, [22,24] , axis=1)
v5 = np.insert(var1 , 2, [22,24,25] , axis=0)

print(v2)
print()
print(v3)
print()
print(v4)
print()
print(v5)

[[1 2 6 3]
 [4 5 6 6]]

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[ 1 22  2  3]
 [ 4 24  5  6]]

[[ 1  2  3]
 [ 4  5  6]
 [22 24 25]]


**Delete**

In [ ]:
var = np.array([1,2,3,4,5,6])

d = np.delete(var , 2)
print(var)
print()
print(d)

[1 2 3 4 5 6]

[1 2 4 5 6]
